---
- name: Create directory to hold Graylog certs
  file:
    path: "/etc/graylog/ssl"
    state: directory
    owner: graylog
    group: graylog
    mode: '0750'

- name: Check if there's a cert we should use
  stat:
    path: "/etc/ssl/{{ ssl_certs_common_name }}"
  register: graylog_ssl_cert_existing

- debug:
    msg: "Variable graylog_ssl_cert_existing: {{ graylog_ssl_cert_existing }}"

- name: Copy existing cert stuff
  command: "cp -R /etc/ssl/{{ ssl_certs_common_name }}/ /etc/graylog/ssl/"
  when: graylog_ssl_cert_existing.stat.exists
