---

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: server.yml

- include: convert-SSL.yml
  when: graylog_convert_ssl
