---
- name: restart graylog-server
  service:
    name: 'graylog-server'
    state: restarted

- name: set permissions on ssl directory
  file:
    path: "{{ graylog_ssl_directory}}"
    mode: '0740'
    owner: graylog
    group: graylog
    recurse: yes
    state: directory
